LIBS=$(TOP)/commons/lib.cma \
     $(TOP)/h_program-lang/lib.cma 

INCLUDEDIRS= $(TOP)/commons $(TOP)/commons_ocollection \
   $(TOP)/external/json-wheel \
   $(TOP)/h_program-lang $(TOP)/h_version-control  \
   $(TOP)/globals \
   $(TOP)/external/ \
   $(TOP)/lang_GENERIC/parsing \
   $(TOP)/lang_GENERIC/analyze \
